SELECT *
FROM DEPARTMENTS;

SELECT COUNT (employee_id)
FROM EMPLOYEES;

SELECT * 
FROM EMPLOYEES
WHERE SALARY > 15000;

SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '01-JAN-2002' AND '31-DEC-2004';

SELECT *
FROM EMPLOYEES
WHERE PHONE_NUMBER NOT LIKE '515%';

SELECT first_name || ' ' || last_name
FROM EMPLOYEES, DEPARTMENTS
WHERE department_name LIKE 'Finance'
ORDER BY first_name ASC, last_name ASC;

SELECT city, state_province, country_name
FROM COUNTRIES
JOIN LOCATIONS ON COUNTRIES.country_id = LOCATIONS.country_id
JOIN REGIONS ON COUNTRIES.region_id = REGIONS.region_id 
WHERE region_name = 'Asia';

SELECT * 
FROM LOCATIONS
WHERE state_province IS NULL;