INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Dolor Sit Amet Incorporated','R5O8','905-9831 Aliquam Street','Atlanta','GA','91781');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Vitae Sodales Inc.','Y5I9','Ap #435-7322 In Av.','Kansas City','KS','13052');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Non Consulting','K0T3','2395 Aliquam Road','Evansville','IN','92424');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Pharetra Nibh Aliquam Institute','N9R3','4406 Curae; Rd.','Wyoming','WY','88086');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Vitae Dolor Donec Incorporated','N7N7','P.O. Box 849, 7810 Nulla Rd.','Auburn','ME','76260');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Semper Egestas PC','C6X9','788-1470 Sem Street','West Valley City','UT','40465');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Lobortis Inc.','T2S9','802-9139 Massa. Ave','Broken Arrow','OK','94110');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Lectus Corporation','V8J3','2353 Ligula. Avenue','Ketchikan','AK','99878');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Risus Donec Inc.','W7Z5','6876 Imperdiet Street','Gary','IN','25638');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Tempor Augue Foundation','F5F2','333-202 Iaculis, Ave','Butte','MT','63238');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Magna Consulting','K3F1','P.O. Box 315, 2718 Nunc Street','Naperville','IL','73035');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Nec Foundation','V0L3','137-1017 Sociis St.','Philadelphia','PA','45247');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Dolor Egestas Associates','N3Z2','Ap #337-7373 Proin Rd.','Nashville','TN','46601');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Nisl Nulla Associates','B9R5','Ap #904-5662 Quam Rd.','Topeka','KS','27275');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Magnis Dis LLC','J7N7','6165 Cubilia Avenue','Waterbury','CT','10986');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Lectus LLC','E9H7','P.O. Box 477, 7612 Etiam Street','Newark','DE','79381');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Ullamcorper Ltd','N7U4','1336 Cursus. Road','Aurora','IL','36396');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Purus Duis Elementum Corporation','B6T1','P.O. Box 495, 8243 Egestas, St.','Sioux City','IA','79760');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Libero LLC','R2S4','P.O. Box 393, 2350 Senectus Ave','Stamford','CT','31804');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Praesent Interdum Ligula LLC','T8J6','6095 Tempus Av.','Duluth','MN','35394');
/*
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Aliquet Metus LLC','S3S3','Ap #254-8843 Turpis Rd.','Virginia Beach','VA','47250');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Fusce Associates','F6Z5','P.O. Box 399, 5959 Lobortis Street','Indianapolis','IN','42441');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Dictum PC','G8U5','3995 Fusce Ave','Wilmington','DE','39023');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Nunc Sed Company','A6T1','4680 Velit. Avenue','Saint Louis','MO','53487');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Aliquet Institute','P1D6','P.O. Box 872, 5425 Ac St.','Independence','MO','55886');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Phasellus Corporation','U9S4','P.O. Box 628, 8675 Magna. Ave','Tallahassee','FL','33033');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Enim Commodo Corporation','Y2T5','Ap #961-9929 Aliquet, Avenue','Newport News','VA','12597');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Semper Egestas Corporation','I2S4','9995 Ante. Street','Idaho Falls','ID','25710');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Dictum Eu Eleifend Industries','U8Y2','P.O. Box 244, 9208 Placerat, Street','Auburn','ME','72040');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Ultrices Vivamus Institute','Z7J9','P.O. Box 392, 1690 Quisque St.','Lakewood','CO','70124');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Ultricies Ligula Corporation','F4Y4','P.O. Box 424, 8296 Fringilla Avenue','Bear','DE','76476');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Amet Consectetuer Institute','A7L9','Ap #287-565 Ut St.','Huntsville','AL','36143');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Nunc Ullamcorper Eu Associates','L4N7','1537 Phasellus Ave','Chicago','IL','26202');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Urna Ut LLP','B7I4','1067 At Avenue','Orlando','FL','13726');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Justo Inc.','L1S4','Ap #179-210 Massa. Street','Bloomington','MN','93856');
INSERT INTO Fridge (ID,brand,model,street,city,state,zipcode) VALUES (fridge_sequence.nextval,'Enim Incorporated','R3Y4','P.O. Box 843, 1917 Ornare Road','Lincoln','NE','17805');
*/

INSERT INTO UserType (ID,name) VALUES (userType_sequence.nextval,'lab');
INSERT INTO UserType (ID,name) VALUES (userType_sequence.nextval,'restaurant');
INSERT INTO UserType (ID,name) VALUES (userType_sequence.nextval,'domestic');

INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'egestas@ligulaNullamfeugiat.edu','CjA83NSM1Sm','Marvin','Chase','739-615-2623',102,100);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'convallis.convallis.dolor@malesuadaut.co.uk','YuN63CRQ6Lw','Geoffrey','Lloyd','970-626-7439',101,102);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'ligula@Suspendisse.org','EkN18UEM6Uc','Tara','Hill','325-402-0160',102,103);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'dictum@quis.edu','YyY95PYY3Du','Yen','Patton','772-885-8955',102,103);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'ridiculus.mus.Proin@ultricies.ca','WmH74KVD8Qv','Kelly','Chapman','479-763-0078',102,104);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'in.consequat.enim@porttitorerosnec.org','EzG95XID9An','Nora','Newton','171-637-2175',100,106);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'urna.Ut.tincidunt@vulputatevelit.org','EoM88XHA7Lr','Bruno','Palmer','457-911-7048',102,107);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'erat.eget.tincidunt@et.ca','AfM97GIE7Pu','Magee','Monroe',NULL,102,107);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'vel.quam.dignissim@tellusNunc.ca','JjH16UOS8Hn','Kimberly','Sandoval','445-872-4423',102,107);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'feugiat.non@justo.edu','BdN06ELU3Eu','Jemima','Carson','720-321-7743',102,107);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'Vivamus.molestie.dapibus@aenimSuspendisse.org','KuN29FJH4Ok','Amena','Bean','358-209-5238',100,108);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'magna@semPellentesque.org','SpL79UDO4Kq','Armand','Murray','688-492-4457',100,108);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'sit@luctusetultrices.co.uk','WcN84BCH2Gt','Bruce','Floyd','479-151-6330',101,111);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'sollicitudin.adipiscing.ligula@In.ca','OqL27ACF7Gx','Richard','Galloway','366-495-5395',102,112);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'sodales.nisi.magna@magna.ca','TmK33JGF0Lm','Aurelia','Hester','235-890-1195',102,112);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'Cras@indolorFusce.co.uk','PkI55PKZ5Rp','Adria','Mejia','371-945-1434',102,112);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'Aliquam.rutrum.lorem@euligulaAenean.edu','LaL63ORF4Pz','Fatima','Walker','464-830-4602',101,113);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'mauris.Integer.sem@Maurisblandit.edu','DfM16BFL2Vx','Baker','Woodard','729-200-3971',101,114);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'blandit.at@diam.net','CnJ82NSA5Mt','Herrod','Brock','207-770-7517',100,115);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'Cum.sociis.natoque@porttitortellusnon.ca','FpR56PEM2Ah','Preston','Cooper','595-474-8011',100,115);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'eget.ipsum@dolorsitamet.edu','EcY40NMS3Eq','Brady','Payne','317-828-4835',100,115);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'enim.Suspendisse.aliquet@magnisdisparturient.org','VlH68OBD2Sl','Uriah','Guy','427-182-2375',100,115);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'Aliquam.nisl.Nulla@volutpatNullafacilisis.ca','JoB62LRP3Oa','Nayda','Britt',NULL,100,115);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'Fusce.aliquet@scelerisqueduiSuspendisse.com','LvL53VOW2Gg','Tucker','Bright','201-329-4956',102,116);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'adipiscing.non@eratSed.org','BgA85HTW8Gu','Hoyt','Huffman','814-720-5605',102,116);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'lacus.varius@et.com','BcL47TYJ9Bw','Levi','Fischer','832-268-8658',102,116);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'ac.mi.eleifend@tristique.edu','SsY27NCJ9Yr','Gretchen','Cruz','935-211-8428',100,117);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'fringilla@ridiculusmusProin.net','ElF51CQU3Ch','Amanda','Sharpe','856-944-3168',100,117);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'sit.amet.ultricies@liberolacusvarius.net','YaH95ILG2Rh','Malachi','Lawrence','483-156-2952',102,118);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'tincidunt@nullaInteger.co.uk','MkP44PXL3Mq','Zachary','Branch','890-517-6903',102,118);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'viverra.Maecenas.iaculis@metusAeneansed.edu','NpJ77KNP9Qt','Kadeem','Bradford','491-210-5608',102,119);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'malesuada@nonummyultricies.org','DwR53RHA3Nl','Teagan','Chase','764-674-6426',102,119);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'egestas.a@porttitorscelerisqueneque.net','JdA77IRL9Ze','Phelan','Garrett','939-739-5787',102,119);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'arcu.Vivamus@nascetur.org','PgJ03ZCS2Gj','Odysseus','Webb',NULL,102,119);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'vel@feugiatnon.ca','SrF80LZC3Ip','Angelica','Mcgee','697-526-2044',102,119);
INSERT INTO Owner (ID,userName,password,firstName,lastName,phoneNumber,userTypeID,fridgeID) VALUES (owner_sequence.nextval,'elit.fermentum@dignissimmagna.org','PzQ72GSL3Iw','Hasad','Jefferson','163-453-7974',102,119);

INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'erat. Sed nunc','aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque','hours',35);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'mollis vitae, posuere at,','placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna','hours',35);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'dictum. Proin eget','Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem.','hours',30);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'sociis natoque penatibus','sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem','minutes',28);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'Donec egestas.','Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu,','minutes',29);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'in molestie','ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia','minutes',25);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'condimentum eget,','amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis','minutes',12);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'id magna et ipsum','mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget','minutes',15);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'mollis. Integer','Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat','hours',44);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'Cum sociis','diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent','hours',31);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'Integer vulputate,','sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula.','minutes',16);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'blandit at,','adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum','minutes',23);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'tempus non,','ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum','hours',26);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'non leo. Vivamus','ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi','minutes',15);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'accumsan laoreet','massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum','minutes',16);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'aliquet. Proin velit. Sed','dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac','hours',26);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'Fusce aliquet','venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci','minutes',18);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'Sed nulla ante, iaculis','habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec','minutes',32);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'ac turpis egestas. Aliquam','Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae','hours',27);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'non lorem','pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec','minutes',31);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'aliquet vel, vulputate','dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat.','minutes',24);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'In faucibus.','ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel,','minutes',19);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'ante lectus convallis','ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam','minutes',20);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'neque. Nullam ut nisi','tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique','hours',31);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'mauris a nunc.','ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi','minutes',36);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'Maecenas libero est, congue','fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy','minutes',25);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'risus. Donec','magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum','hours',38);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'ipsum leo','felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a','hours',36);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'vel, mauris.','nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu.','hours',39);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'Donec at arcu. Vestibulum','Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut','hours',33);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'ut lacus.','felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus','minutes',36);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'nec ante','et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate','hours',40);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'tincidunt aliquam arcu. Aliquam','vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis','minutes',15);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'tortor at risus.','risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede.','minutes',10);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'feugiat. Sed nec metus','interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet,','hours',26);
INSERT INTO Recipe (ID,name,description,durationUnit,durationNumber) VALUES (recipe_sequence.nextval,'sapien. Nunc','at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget','hours',34);

INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'berries', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'huckleberries', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'mackerel', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'monkfish', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'lemon Peel', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'acetaldehyde', 'lab');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'bouillon', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'Marsala', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'venison', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'carrots', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'hoisin sauce', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'red cabbage', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'olives', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'salt', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'cherries', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'sesame seeds', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'blueberries', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'bay leaves', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'benzene', 'lab');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'herring', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'prunes', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'chicken', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'bacon', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'toluene', 'lab');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'coconuts', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'acetone', 'lab');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'vanilla bean', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'coconut oil', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'wild rice', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'pentane', 'lab');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'date sugar', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'jelly beans', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'brazil nuts', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'Ethyl alcohol', 'lab');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'Romano cheese', 'food');
INSERT INTO Ingredient (ID,name, kind) VALUES (ingredient_sequence.nextval,'chocolate', 'food');

INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'27-Dec-2017',100,100);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'12-Oct-2017',112,100);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'18-Feb-2018',102,100);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'28-Nov-2017',130,100);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'19-Oct-2017',132,100);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'27-Dec-2017',126,102);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'12-Oct-2017',124,102);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'18-Feb-2018',102,102);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'28-Nov-2017',127,102);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'19-Oct-2017',121,102);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'09-Dec-2017',135,102);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'14-Oct-2017',101,103);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'28-Nov-2017',127,103);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'19-Oct-2017',121,103);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'09-Dec-2017',111,103);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'02-Nov-2017',122,104);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'07-Nov-2017',133,106);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'19-Jan-2018',125,106);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'20-Jan-2018',123,106);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'02-Nov-2017',105,106);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'26-Dec-2017',118,106);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'21-Feb-2018',119,107);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'21-Feb-2018',102,107);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'21-Feb-2018',100,107);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'21-Feb-2018',101,107);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'21-Feb-2018',104,107);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'14-Jan-2018',105,108);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'18-Feb-2018',133,108);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'18-Feb-2018',120,111);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'26-Feb-2018',134,112);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'26-Feb-2018',100,112);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'26-Feb-2018',127,112);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'04-Jan-2018',107,112);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'10-Dec-2017',122,113);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'28-Nov-2017',110,113);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'06-Mar-2018',111,113);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'07-Jan-2018',109,114);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'07-Jan-2018',133,115);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'07-Jan-2018',105,115);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'07-Jan-2018',123,115);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'07-Jan-2018',125,115);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'07-Jan-2018',129,115);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'07-Jan-2018',118,115);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'28-Nov-2017',132,116);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'18-Nov-2017',135,116);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'28-Nov-2017',129,117);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'18-Nov-2017',105,117);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'08-Feb-2018',111,118);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'07-Feb-2018',114,118);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'04-Feb-2018',122,118);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'16-Nov-2017',100,118);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'23-Nov-2017',104,119);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'12-Feb-2018',124,119);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'07-Feb-2018',117,119);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'28-Nov-2017',108,119);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'08-Feb-2018',116,119);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'07-Feb-2018',114,119);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'04-Feb-2018',102,119);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'16-Nov-2017',100,119);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'12-Nov-2017',115,119);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'19-Oct-2017',103,119);
INSERT INTO Stock (RFID,expirationDate,ingredientID,fridgeID) VALUES (stock_sequence.nextval,'01-Nov-2017',101,119);

INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (100,105);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (101,101);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (102,100);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (102,119);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (103,117);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (104,101);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (105,130);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (106,121);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (107,132);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (107,131);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (108,114);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (109,127);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (110,116);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (110,101);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (110,125);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (111,129);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (111,110);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (111,113);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (112,103);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (112,118);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (113,125);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (114,106);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (116,120);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (117,118);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (118,107);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (118,115);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (118,129);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (119,108);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (119,128);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (119,123);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (119,119);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (119,100);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (120,107);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (120,113);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (121,132);
INSERT INTO OwnerRecipe (ownerID,recipeID) VALUES (121,109);

INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (100,118,'fl oz',3);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (100,123,'cup',1);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (103,119,'tablespoon',3);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (103,121,'teaspoon',1);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (104,113,'pint',4);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (106,108,'teaspoon',4);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (107,127,'lb',1);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (108,105,'pint',3);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (110,110,'tablespoon',3);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (111,121,'teaspoon',4);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (111,115,'cup',4);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (112,123,'fl oz',1);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (112,118,'lb',1);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (114,119,'teaspoon',4);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (118,104,'pint',1);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (119,118,'teaspoon',5);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (120,110,'teaspoon',2);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (121,116,'fl oz',3);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (122,120,'teaspoon',5);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (123,105,'tablespoon',2);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (123,123,'teaspoon',2);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (123,129,'fl oz',1);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (125,107,'cup',1);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (126,103,'fl oz',1);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (127,122,'teaspoon',3);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (127,109,'teaspoon',5);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (128,105,'lb',4);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (128,129,'lb',1);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (128,123,'teaspoon',4);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (129,124,'teaspoon',3);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (130,129,'pint',4);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (131,113,'cup',3);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (132,126,'pint',3);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (133,102,'lb',5);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (134,127,'pint',1);
INSERT INTO RecipeIngredient (recipeID,ingredientID,unit,quantity) VALUES (135,103,'teaspoon',2);

-- Lab OwnerStock
INSERT INTO OwnerStock (ownerID,stockID) VALUES (105,116);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (105,117);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (105,118);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (105,119);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (105,120);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (110,126);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (110,127);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (111,127);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (118,138);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (120,138);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (122,138);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (119,139);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (120,140);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (121,141);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (118,142);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (122,142);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (126,146);
-- Food OwnerStock
INSERT INTO OwnerStock (ownerID,stockID) VALUES (100,100);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (100,102);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (100,103);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (100,104);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (101,105);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (101,107);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (101,108);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (101,109);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (101,110);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (103,111);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (102,112);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (103,112);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (102,113);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (103,114);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (104,115);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (106,121);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (107,122);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (109,123);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (109,124);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (109,125);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (112,128);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (113,129);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (113,130);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (113,131);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (114,131);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (113,132);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (114,132);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (116,133);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (116,134);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (116,135);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (117,136);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (124,143);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (124,144);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (128,147);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (128,148);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (128,149);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (128,150);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (129,147);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (129,148);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (129,149);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (129,150);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (130,151);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (135,151);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (130,152);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (131,153);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (131,154);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (132,155);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (132,156);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (134,157);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (134,158);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (131,159);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (130,160);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (135,161);
INSERT INTO OwnerStock (ownerID,stockID) VALUES (134,161);